const STORAGE_KEY='azfitness-allin-v3';
const AUTH_KEY='azfitness-auth-v2';
const todayName=new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date());
const foodDB=[
 {name:'Banana',serving:'1 medium',cal:105,protein:1,carbs:27,fat:.4,water:118}, {name:'Apple',serving:'1 medium',cal:95,protein:.5,carbs:25,fat:.3,water:156},
 {name:'Egg',serving:'1 large',cal:72,protein:6,carbs:.4,fat:5,water:38}, {name:'Oatmeal cooked',serving:'1 cup',cal:154,protein:6,carbs:27,fat:3,water:198},
 {name:'Greek yogurt plain',serving:'1 cup',cal:130,protein:22,carbs:9,fat:1,water:215}, {name:'Chicken breast cooked',serving:'4 oz',cal:187,protein:35,carbs:0,fat:4,water:80},
 {name:'Turkey sandwich',serving:'1 sandwich',cal:320,protein:25,carbs:38,fat:8,water:120}, {name:'Brown rice cooked',serving:'1 cup',cal:216,protein:5,carbs:45,fat:2,water:145},
 {name:'Salmon cooked',serving:'4 oz',cal:233,protein:25,carbs:0,fat:14,water:72}, {name:'Broccoli cooked',serving:'1 cup',cal:55,protein:4,carbs:11,fat:.6,water:156},
 {name:'Whole milk',serving:'1 cup',cal:149,protein:8,carbs:12,fat:8,water:215}, {name:'Water',serving:'16 oz',cal:0,protein:0,carbs:0,fat:0,water:473},
 {name:'Peanut butter',serving:'2 tbsp',cal:190,protein:8,carbs:7,fat:16,water:3}, {name:'Whey protein shake',serving:'1 scoop',cal:120,protein:24,carbs:3,fat:2,water:300}
];
const goalOptions=['bulk up','strengthen core','lose fat','walk more','run faster','train athletic','yoga mobility','meditate/breathe','conditioning','build muscle','better posture','family hike','sports performance','recover/sleep'];
const workouts=[
 plan('strength-gold','Gold Strength Builder','Strength','bulk up, build muscle, train athletic','medium',38,[ex('Squat Matrix','legs/core','4 sets','10 reps',{rep:'squat',target:90},['knees track toes','chest tall','hips below parallel']),ex('Push-Up Ladder','chest/core','4 sets','6-12 reps',{rep:'pushup',target:85},['body straight','elbows tucked']),ex('Backpack Row','back/biceps','4 sets','12 reps',{rep:'row',target:120},['pull elbows to pockets'])]),
 plan('core-armor','Core Armor','Core','strengthen core, better posture','medium',28,[ex('Dead Bug','deep core','3 sets','8/side',{rep:'core',target:90},['ribs down','slow exhale']),ex('Bear Plank Taps','core/shoulders','4 sets','10/side',{rep:'tap',target:90},['hips quiet']),ex('Side Plank','obliques','3 sets','30 sec',{rep:'hold',target:180},['long line','breathe'])]),
 plan('run-walk','Run/Walk Route Mission','Cardio','walk more, run faster, family hike','low',35,[ex('Warm Walk','heart/legs','1','5 min',{rep:'walk',target:0},['easy pace']),ex('Intervals','heart/legs','8 rounds','1 min jog + 90 sec walk',{rep:'route',target:0},['smooth stride','talk-test']),ex('Cooldown','recovery','1','5 min',{rep:'walk',target:0},['slow breathing'])]),
 plan('mobility-yoga','Gold Mobility Yoga','Mobility','yoga mobility, recover/sleep, meditate/breathe','low',24,[ex('World Greatest Stretch','hips/spine','3 sets','5/side',{rep:'mobility',target:100},['rotate open']),ex('Couch Stretch','hips/quads','2 sets','45 sec',{rep:'hold',target:180},['squeeze glute']),ex('Box Breathing','diaphragm','5 rounds','4-4-4-4',{rep:'breath',target:0},['quiet shoulders'])]),
 plan('condition','Athlete Conditioning','Conditioning','conditioning, sports performance, lose fat','high',32,[ex('Soft Jacks','heart/calves','5 sets','40 sec',{rep:'jump',target:0},['land quiet']),ex('Reverse Lunge','legs/glutes','4 sets','8/side',{rep:'lunge',target:95},['front knee tracks']),ex('Mountain Climber','core/cardio','4 sets','30 sec',{rep:'climber',target:90},['shoulders over wrists'])])
];
function plan(id,title,cat,goals,load,duration,exercises){return{id,title,cat,goals,load,duration,exercises}};function ex(name,muscles,sets,reps,pose,cues){return{name,muscles,sets,reps,pose,cues}};
let state=loadState(), auth=loadAuth(), tab=auth.profileId?'home':'login', routeWatch=null, camera={stream:null,timer:null,pose:null,seconds:0,events:[],reps:0,repOpen:true,currentExercise:null,lastAngles:null,health:{}};
function defaults(){let z=crypto.randomUUID(), c=crypto.randomUUID(); return {profiles:[profile(z,'Zayne',13),profile(c,'CAK3D',35)],logs:[],meals:[],water:[],photos:[],routes:[],customWorkouts:[],activeRoutine:null};}
function profile(id,name,age){return{id,name,birthday:'',sex:'',heightFt:5,heightIn:0,weightLb:name==='Zayne'?100:190,age,level:'medium',goals:['build muscle','walk more'],limitations:'',pinHash:null,pic:''};}
function migrate(s){s.profiles??=[];s.logs??=[];s.meals??=[];s.water??=[];s.photos??=[];s.routes??=[];s.customWorkouts??=[];s.profiles.forEach(p=>{p.heightFt??=Math.floor((p.heightCm? p.heightCm/2.54:60)/12);p.heightIn??=Math.round((p.heightCm? p.heightCm/2.54:60)%12);p.weightLb??=Math.round((p.weightKg||70)*2.20462);p.birthday??='';p.sex??='';p.pic??='';p.goals??=[];});return s;}
function loadState(){try{return migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return defaults()}}function loadAuth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY))||{profileId:null}}catch{return{profileId:null}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));localStorage.setItem(AUTH_KEY,JSON.stringify(auth));}
function p(){return state.profiles.find(x=>x.id===auth.profileId)||state.profiles[0]}function logs(){return state.logs.filter(l=>l.profileId===p().id)}function today(){return new Date().toDateString()}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function $(s){return document.querySelector(s)}function val(s){return $(s)?.value||''}
async function hashPin(pin){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('azfit:'+pin));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function ageOf(pr=p()){if(pr.birthday){let b=new Date(pr.birthday),n=new Date(),a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a}return +pr.age||0}function weightKg(pr=p()){return (pr.weightLb||0)*.453592}function heightIn(pr=p()){return (+pr.heightFt||0)*12+(+pr.heightIn||0)}function bmi(){let h=heightIn();return h?((p().weightLb/(h*h))*703).toFixed(1):'--'}
function calNeed(pr=p()){let kg=weightKg(pr), cm=heightIn(pr)*2.54, age=ageOf(pr), sex=pr.sex==='female'?-161:5, bmr=10*kg+6.25*cm-5*age+sex, mult={low:1.35,medium:1.55,high:1.75}[pr.level]||1.45; let goal=(pr.goals||[]).join(' '); let adj=goal.includes('bulk')||goal.includes('muscle')?250:goal.includes('lose')?-250:0; return Math.round(bmr*mult+adj)}
function render(){save(); if(!auth.profileId)return login(); const pr=p(); document.body.dataset.gold='1'; $('#app').innerHTML=`<main class="app-shell"><aside class="side card"><div class="brand"><span class="crest">A-Z</span><div><b>A-Z FITNESS</b><small>${esc(pr.name)} • ${pr.level} week</small></div></div>${['home','plan','coach','route','fuel','timeline','profile'].map(t=>`<button class="nav ${tab===t?'active':''}" data-tab="${t}">${navLabel(t)}</button>`).join('')}<button class="nav ghost" id="logout">Log out / switch athlete</button><p class="tiny warning">Vitals are camera/GPS estimates, not medical devices.</p></aside><section class="main-stage"><header class="topbar card"><div><p class="eyebrow">BLACK • YELLOW • GOLD • A-Z JOURNEY</p><h1>${headline(tab)}</h1></div><div class="athlete-chip">${pr.pic?`<img src="${pr.pic}">`:`<span>${esc(pr.name[0])}</span>`}<div><b>${esc(pr.name)}</b><small>${ageOf(pr)} yrs • ${pr.heightFt}'${pr.heightIn}" • ${pr.weightLb} lb • BMI ${bmi()}</small></div></div></header><section id="panel"></section></section></main>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#logout').onclick=()=>{auth.profileId=null;tab='login';render()};({home,planPage,coach,route,fuel,timeline,profilePage}[tab])();}
function navLabel(t){return{home:'⌁ Dashboard',plan:'◆ Plan + Builder',coach:'◎ Live Coach',route:'⌖ GPS Routes',fuel:'◒ Food + Meals',timeline:'▰ Journey Timeline',profile:'◈ Profile'}[t]}function headline(t){return{home:'Command center',plan:'Choose, generate, customize',coach:'Step-by-step camera rep coach',route:'Run/walk live map',fuel:'Diet plan, foods, recipes',timeline:'History, photos, improvements',profile:'Athlete setup'}[t]}
function login(){let opts=state.profiles.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#app').innerHTML=`<main class="login-wrap"><section class="login-card card glow"><div class="logo-xl">A-Z</div><p class="eyebrow">SECURE GOLD ACCESS</p><h1>Log in before switching profiles.</h1><p class="muted">Pick your name. First login PIN is <b>0000</b>, then choose and verify your 4-digit PIN.</p><label>Name<select id="who">${opts}</select></label><label>PIN<input id="pin" inputmode="numeric" maxlength="4" type="password" placeholder="0000"></label><div id="setpin"><label>New PIN<input id="newpin" inputmode="numeric" maxlength="4" type="password"></label><label>Verify PIN<input id="verpin" inputmode="numeric" maxlength="4" type="password"></label></div><button id="unlock">Unlock</button><p id="msg" class="tiny"></p></section></main>`;function sync(){let pr=state.profiles.find(x=>x.id===val('#who'));$('#setpin').hidden=!!pr.pinHash}$('#who').onchange=sync;sync();$('#unlock').onclick=async()=>{let pr=state.profiles.find(x=>x.id===val('#who')), pin=val('#pin');if(!/^\d{4}$/.test(pin))return $('#msg').textContent='Use a 4 digit PIN.';if(!pr.pinHash){if(pin!=='0000')return $('#msg').textContent='First login PIN is 0000.';if(!/^\d{4}$/.test(val('#newpin'))||val('#newpin')!==val('#verpin'))return $('#msg').textContent='New PINs must match.';pr.pinHash=await hashPin(val('#newpin'));}else if(await hashPin(pin)!==pr.pinHash)return $('#msg').textContent='Wrong PIN.';auth.profileId=pr.id;tab='home';render();};}
function home(){let pr=p(), ls=logs(), t=totals();$('#panel').innerHTML=`<section class="deck-grid"><article class="card hero-gold"><p class="eyebrow">TODAY'S ASK</p><h2>What do you want to do?</h2><div class="chips">${goalOptions.map(g=>`<button class="chip" data-goal="${g}">${g}</button>`).join('')}</div><div id="suggestions"></div></article><article class="card"><h2>Readiness</h2><div class="tile-grid"><div><span>Calories target</span><b>${calNeed(pr)}</b></div><div><span>Weekly load</span><b>${pr.level}</b></div><div><span>Workouts</span><b>${t.workouts}</b></div><div><span>Miles</span><b>${t.miles.toFixed(1)}</b></div></div></article><article class="card"><h2>Quick generators</h2><label>Type anything: workout, meal, goal, soreness...<input id="genText" placeholder="I want stronger core and better mile time"></label><button id="genBtn">Generate response</button><div id="genOut" class="answer"></div></article><article class="card"><h2>Progress graph</h2><canvas id="homeChart" height="230"></canvas></article></section>`;document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>suggest(b.dataset.goal));$('#genBtn').onclick=()=>generate(val('#genText'));drawChart('homeChart',series(),['Minutes','Miles x10','Calories/50']);}
function suggest(goal){let list=allWorkouts().filter(w=>w.goals.includes(goal.split(' ')[0])||w.goals.includes(goal)).slice(0,3);if(!list.length)list=allWorkouts().slice(0,3);$('#suggestions').innerHTML=`<h3>Suggested for ${esc(goal)}</h3>${list.map(w=>`<article class="log"><b>${w.title}</b><span>${w.cat} • ${w.load} • ${w.duration} min</span><button data-start="${w.id}">Start onboarding</button></article>`).join('')}`;document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startRoutine(b.dataset.start));}
function generate(text){let pr=p(), q=text.toLowerCase();let msg=q.includes('meal')||q.includes('food')?mealPlanText(pr):q.includes('sore')?`Recovery plan: 20 min mobility, ${Math.round(pr.weightLb*.55)} oz water, protein at each meal, and easy zone-2 walk.`:q.includes('run')||q.includes('mile')?`Running block: 3 days/week. One easy walk/run, one interval day, one longer route. Start GPS Routes and keep average speed visible in mph.`:`A-Z plan: choose ${pr.level} weekly load, train 3-5 days, log food/water, take before/after photos, and use Live Coach for rep/form counting.`;$('#genOut').innerHTML=`<p>${esc(msg)}</p>`;}
function planPage(){let pr=p();$('#panel').innerHTML=`<section class="deck-grid"><article class="card wide"><h2>Weekly workout choice</h2><div class="seg"><button data-load="low">Low</button><button data-load="medium">Medium</button><button data-load="high">High</button></div><p class="muted">Current: ${pr.level}</p><div class="chips">${goalOptions.map(g=>`<button class="chip goalpick" data-goal="${g}">${g}</button>`).join('')}</div></article><article class="card"><h2>Pre-built library</h2><div id="workoutList">${allWorkouts().map(workoutCard).join('')}</div></article><article class="card"><h2>Custom workout</h2><label>Name<input id="cwName" placeholder="Zayne Core Blast"></label><label>Goal<input id="cwGoal" placeholder="core, strength"></label><label>Exercises<textarea id="cwEx" placeholder="Squats 3x10\nPushups 3x8"></textarea></label><button id="saveCw">Save custom</button></article><article class="card wide" id="routineBox"><h2>Step-by-step onboarding</h2><p>Pick a workout to start.</p></article></section>`;document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{pr.level=b.dataset.load;render()});document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startRoutine(b.dataset.start));$('#saveCw').onclick=saveCustom;}
function allWorkouts(){return [...workouts,...state.customWorkouts]}function workoutCard(w){return`<article class="log"><b>${esc(w.title)}</b><span>${w.cat} • ${w.load} • ${w.duration} min</span><p>${esc(w.goals)}</p><button data-start="${w.id}">Start</button></article>`}function saveCustom(){let lines=val('#cwEx').split('\n').filter(Boolean);let w=plan('custom-'+crypto.randomUUID(),val('#cwName')||'Custom Workout','Custom',val('#cwGoal')||'custom',p().level,30,lines.map(x=>ex(x,'custom','custom','custom',{rep:'custom',target:90},['clean form','steady breathing'])));state.customWorkouts.unshift(w);render();}
function startRoutine(id){let w=allWorkouts().find(x=>x.id===id)||workouts[0];state.activeRoutine={id:w.id,step:0,start:Date.now(),reps:0,statsBefore:{weightLb:p().weightLb,heart:camera.health.heart||null},photos:[]};tab='coach';render();}
function coach(){let r=state.activeRoutine,w=r?allWorkouts().find(x=>x.id===r.id):allWorkouts()[0], step=r?.step||0, exx=w.exercises[step]||w.exercises[0];camera.currentExercise=exx;$('#panel').innerHTML=`<section class="coach-layout"><article class="card camera-card"><h2>${r?'Step '+(step+1)+' / '+w.exercises.length:'Live Coach'}</h2><h3>${esc(exx.name)}</h3><p>${esc(exx.sets)} • ${esc(exx.reps)} • ${esc(exx.muscles)}</p><div class="video-box"><video id="video" playsinline muted></video><canvas id="overlay" width="960" height="720"></canvas></div><div class="actions"><button id="startCam">Start camera + rep counter</button><button id="prevStep">Prev</button><button id="nextStep">Next step</button><button id="finishRoutine">Finish + save</button></div><p class="cue" id="cue">${exx.cues.map(esc).join(' • ')}</p></article><article class="card"><h2>Live readout</h2><div class="big-reps"><b id="repCount">${camera.reps}</b><span>reps counted</span></div><div id="liveMetrics" class="tile-grid"></div><h3>Joint angles</h3><div id="angles"></div><h3>Corrections</h3><div id="events"></div></article></section>`;$('#startCam').onclick=startCamera;$('#nextStep').onclick=()=>{if(!state.activeRoutine)state.activeRoutine={id:w.id,step:0,start:Date.now(),reps:0};state.activeRoutine.step=Math.min(w.exercises.length-1,(state.activeRoutine.step||0)+1);render()};$('#prevStep').onclick=()=>{state.activeRoutine.step=Math.max(0,(state.activeRoutine.step||0)-1);render()};$('#finishRoutine').onclick=finishRoutine;renderLiveMetrics();renderEvents();}
function finishRoutine(){let r=state.activeRoutine,w=allWorkouts().find(x=>x.id===r?.id)||workouts[0];camera.stream?.getTracks().forEach(t=>t.stop());saveLog(w,camera.events,{duration:Math.max(1,Math.round(((Date.now()-(r?.start||Date.now()))/60000)||w.duration)),effort:{low:2,medium:3,high:4}[w.load]||3,notes:`Completed ${w.title}. Reps counted: ${camera.reps}.`,reps:camera.reps,before:r?.statsBefore,after:{weightLb:p().weightLb,heart:camera.health.heart||null}});state.activeRoutine=null;camera.reps=0;tab='timeline';render();}
async function loadPose(){if(camera.pose)return camera.pose;try{const m=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const v=await m.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');camera.pose=await m.PoseLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task'},runningMode:'VIDEO',numPoses:1});return camera.pose}catch(e){return null}}
async function startCamera(){let video=$('#video'), cue=$('#cue');try{camera.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});video.srcObject=camera.stream;await video.play()}catch(e){cue.textContent='Camera blocked: '+e.message;return}camera.pose=await loadPose();camera.seconds=0;camera.timer=setInterval(scanFrame,250)}
function pt(lm,i,c){let q=lm[i];return{x:q.x*c.width,y:q.y*c.height,z:q.z||0}}function angle(a,b,c){let A=Math.atan2(a.y-b.y,a.x-b.x),C=Math.atan2(c.y-b.y,c.x-b.x),d=Math.abs((A-C)*180/Math.PI);return d>180?360-d:d}
function scanFrame(){let video=$('#video'), canvas=$('#overlay');if(!video||!video.videoWidth)return;let ctx=canvas.getContext('2d');ctx.drawImage(video,0,0,canvas.width,canvas.height);let lm=null;if(camera.pose){try{lm=camera.pose.detectForVideo(video,performance.now()).landmarks?.[0]}catch{}}if(lm){drawPose(ctx,lm,canvas);analyze(lm,canvas)}else fallback(ctx,canvas);renderLiveMetrics();}
function drawPose(ctx,lm,c){ctx.strokeStyle='#ffd700';ctx.lineWidth=6;[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,25],[25,27],[24,26],[26,28],[23,24]].forEach(([a,b])=>{let A=pt(lm,a,c),B=pt(lm,b,c);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke()})}
function analyze(lm,c){let L={lKnee:angle(pt(lm,23,c),pt(lm,25,c),pt(lm,27,c)),rKnee:angle(pt(lm,24,c),pt(lm,26,c),pt(lm,28,c)),lElbow:angle(pt(lm,11,c),pt(lm,13,c),pt(lm,15,c)),rElbow:angle(pt(lm,12,c),pt(lm,14,c),pt(lm,16,c))};camera.lastAngles=L;let exx=camera.currentExercise||{};let metric=exx.pose?.rep==='pushup'?Math.min(L.lElbow,L.rElbow):Math.min(L.lKnee,L.rKnee);if(metric<105&&camera.repOpen){camera.reps++;camera.repOpen=false;if($('#repCount'))$('#repCount').textContent=camera.reps}if(metric>150)camera.repOpen=true;let posture=100-Math.abs(pt(lm,11,c).y-pt(lm,12,c).y)/3;camera.health={heart:'proxy scan',breath:'motion scan',pupil:'focus proxy',posture:Math.round(posture),angles:L};$('#angles')&&( $('#angles').innerHTML=Object.entries(L).map(([k,v])=>`<p class="angle-row"><b>${k}</b><span>${Math.round(v)}°</span></p>`).join(''));if(posture<75&&camera.events.length<12){camera.events.unshift({second:Math.round(camera.seconds),message:'Square shoulders/hips and slow down.'});renderEvents();}camera.seconds+=.25;}
function fallback(ctx,c){ctx.strokeStyle='#ffd700';ctx.lineWidth=6;ctx.strokeRect(c.width*.22,c.height*.08,c.width*.56,c.height*.78);ctx.fillStyle='#ffd700';ctx.font='24px sans-serif';ctx.fillText('Pose guide loading / fallback',30,c.height-30);camera.health={heart:'calibrating',breath:'calibrating',pupil:'face proxy',posture:'fallback'}}function renderLiveMetrics(){let h=camera.health||{};let box=$('#liveMetrics');if(box)box.innerHTML=`<div><span>Heart</span><b>${h.heart||'--'}</b></div><div><span>Breath</span><b>${h.breath||'--'}</b></div><div><span>Pupil/focus</span><b>${h.pupil||'--'}</b></div><div><span>Posture</span><b>${h.posture||'--'}</b></div>`}function renderEvents(){let e=$('#events');if(e)e.innerHTML=camera.events.length?camera.events.map(x=>`<article class="event"><b>${x.second||0}s</b><p>${esc(x.message)}</p></article>`).join(''):'<p>No corrections yet.</p>'}
function route(){let active=!!routeWatch;$('#panel').innerHTML=`<section class="deck-grid"><article class="card wide"><h2>GPS route tracker</h2><div class="actions"><button id="startRoute">Start walk/run</button><button id="stopRoute">Stop + save</button></div><div class="tile-grid"><div><span>Miles</span><b id="routeMiles">0.00</b></div><div><span>Speed</span><b id="routeMph">0.0 mph</b></div><div><span>Points</span><b id="routePts">0</b></div><div><span>Status</span><b>${active?'tracking':'ready'}</b></div></div><canvas id="routeMap" height="320"></canvas></article><article class="card wide"><h2>Saved routes</h2>${state.routes.filter(r=>r.profileId===p().id).map(r=>`<article class="log"><b>${new Date(r.date).toLocaleString()}</b><span>${r.miles.toFixed(2)} mi • avg ${r.mph.toFixed(1)} mph • ${r.points.length} GPS points</span><canvas class="mini-route" data-route="${r.id}" height="120"></canvas></article>`).join('')||'<p>No routes yet.</p>'}</article></section>`;$('#startRoute').onclick=startRoute;$('#stopRoute').onclick=stopRoute;drawRouteMap(state.currentRoute?.points||[]);setTimeout(drawMiniRoutes,50)}
function startRoute(){state.currentRoute={profileId:p().id,date:new Date().toISOString(),points:[],start:Date.now()};routeWatch=navigator.geolocation.watchPosition(pos=>{let q={lat:pos.coords.latitude,lng:pos.coords.longitude,t:Date.now(),speed:pos.coords.speed};state.currentRoute.points.push(q);updateRouteUI();},{},{enableHighAccuracy:true,maximumAge:1000});route();}
function stopRoute(){if(routeWatch!=null)navigator.geolocation.clearWatch(routeWatch);routeWatch=null;let pts=state.currentRoute?.points||[], miles=routeMiles(pts), hrs=(Date.now()-(state.currentRoute?.start||Date.now()))/3600000;state.routes.unshift({id:crypto.randomUUID(),profileId:p().id,date:new Date().toISOString(),points:pts,miles:miles,mph:miles/(hrs||1)});state.currentRoute=null;route();}
function routeMiles(pts){let m=0;for(let i=1;i<pts.length;i++)m+=dist(pts[i-1],pts[i]);return m}function dist(a,b){let R=3958.8,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180,h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}function updateRouteUI(){let pts=state.currentRoute.points,m=routeMiles(pts),hrs=(Date.now()-state.currentRoute.start)/3600000;$('#routeMiles')&&($('#routeMiles').textContent=m.toFixed(2));$('#routeMph')&&($('#routeMph').textContent=(m/(hrs||1)).toFixed(1)+' mph');$('#routePts')&&($('#routePts').textContent=pts.length);drawRouteMap(pts)}
function drawRouteMap(pts,id='routeMap'){let c=document.getElementById(id);if(!c)return;let ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=(+c.getAttribute('height')||300)*devicePixelRatio;ctx.fillStyle='#080808';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(255,215,0,.2)';for(let x=0;x<w;x+=40)for(let y=0;y<h;y+=40)ctx.strokeRect(x,y,40,40);if(pts.length<2){ctx.fillStyle='#ffd700';ctx.fillText('GPS route draws here live',20,40);return}let minLat=Math.min(...pts.map(p=>p.lat)),maxLat=Math.max(...pts.map(p=>p.lat)),minLng=Math.min(...pts.map(p=>p.lng)),maxLng=Math.max(...pts.map(p=>p.lng));ctx.strokeStyle='#ffd700';ctx.lineWidth=5;ctx.beginPath();pts.forEach((q,i)=>{let x=30+(q.lng-minLng)/((maxLng-minLng)||1)*(w-60),y=h-30-(q.lat-minLat)/((maxLat-minLat)||1)*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}function drawMiniRoutes(){document.querySelectorAll('.mini-route').forEach(c=>{let r=state.routes.find(x=>x.id===c.dataset.route);drawRouteMap(r?.points||[],c.id||(c.id='r'+r.id))})}
async function searchFoods(q){let local=foodDB.filter(f=>f.name.toLowerCase().includes(q.toLowerCase())).slice(0,8);try{let res=await fetch('https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(q)+'&search_simple=1&action=process&json=1&page_size=6');let j=await res.json();let off=(j.products||[]).map(x=>({name:x.product_name||x.generic_name,serving:x.serving_size||'100 g',cal:Math.round(x.nutriments?.['energy-kcal_100g']||0),protein:Math.round(x.nutriments?.proteins_100g||0),carbs:Math.round(x.nutriments?.carbohydrates_100g||0),fat:Math.round(x.nutriments?.fat_100g||0),water:0})).filter(x=>x.name&&x.cal);return[...local,...off].slice(0,10)}catch{return local}}
function fuel(){let pr=p();$('#panel').innerHTML=`<section class="deck-grid"><article class="card"><h2>Food search</h2><label>What did you eat/drink?<input id="foodQ" placeholder="banana, chicken, Gatorade"></label><button id="foodSearch">Find foods</button><div id="foodResults"></div></article><article class="card"><h2>Meal plan generator</h2><p>Target: <b>${calNeed(pr)} calories/day</b></p><button id="mealPlan">Generate meal plan + recipes</button><div id="mealOut"></div></article><article class="card"><h2>Water</h2><button data-water="8">+8 oz</button><button data-water="16">+16 oz</button><button data-water="24">+24 oz</button><p>${waterOz()} oz today</p></article><article class="card wide"><h2>Today intake</h2><div id="mealList"></div></article></section>`;$('#foodSearch').onclick=async()=>showFood(await searchFoods(val('#foodQ')));$('#mealPlan').onclick=()=>$('#mealOut').innerHTML=mealPlanHtml(pr);document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{state.water.unshift({profileId:p().id,date:new Date().toISOString(),oz:+b.dataset.water});fuel()});renderMeals();}
function showFood(list){$('#foodResults').innerHTML=list.map((f,i)=>`<article class="log"><b>${esc(f.name)}</b><span>${f.serving} • ${f.cal} cal • P ${f.protein}g C ${f.carbs}g F ${f.fat}g</span><label>Amount multiplier<input id="amt${i}" type="number" value="1" step=".25"></label><button data-food="${i}">Add</button></article>`).join('');document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>{let f=list[+b.dataset.food],m=+val('#amt'+b.dataset.food)||1;state.meals.unshift({profileId:p().id,date:new Date().toISOString(),...f,amount:m,cal:Math.round(f.cal*m),protein:Math.round(f.protein*m),carbs:Math.round(f.carbs*m),fat:Math.round(f.fat*m)});fuel()})}
function mealPlanText(pr){return`Meal timing for ${pr.name}: breakfast within 90 min, lunch protein/carb, pre-workout snack, dinner recovery. Target ${calNeed(pr)} calories, ${Math.round(pr.weightLb*.75)}g protein, water ${Math.round(pr.weightLb*.55)} oz.`}function mealPlanHtml(pr){let c=calNeed(pr);return`<ol><li><b>Breakfast (${Math.round(c*.25)} cal):</b> eggs/oats/fruit. Recipe: oats + Greek yogurt + berries.</li><li><b>Lunch (${Math.round(c*.3)} cal):</b> chicken rice bowl with broccoli.</li><li><b>Pre-workout (${Math.round(c*.12)} cal):</b> banana + yogurt or peanut butter toast.</li><li><b>Dinner (${Math.round(c*.28)} cal):</b> salmon/chicken, potato/rice, vegetables.</li><li><b>Recovery (${Math.round(c*.05)} cal):</b> milk/protein smoothie if protein is low.</li></ol><p>${mealPlanText(pr)}</p>`}function renderMeals(){let day=today(),ms=state.meals.filter(m=>m.profileId===p().id&&new Date(m.date).toDateString()===day);$('#mealList').innerHTML=ms.length?ms.map(m=>`<article class="log"><b>${esc(m.name)}</b><span>${m.amount||1}x • ${m.cal} cal • P ${m.protein} C ${m.carbs} F ${m.fat}</span></article>`).join(''):'<p>No food yet.</p>'}function waterOz(){return state.water.filter(w=>w.profileId===p().id&&new Date(w.date).toDateString()===today()).reduce((a,w)=>a+w.oz,0)}
function timeline(){let ls=logs();$('#panel').innerHTML=`<section class="deck-grid"><article class="card"><h2>Progress photos</h2><label>Before/after/workout photo<input id="photo" type="file" accept="image/*" capture="environment"></label><label>Note<input id="photoNote" placeholder="before workout, after run..."></label><button id="savePhoto">Save photo</button><div class="photo-grid">${state.photos.filter(x=>x.profileId===p().id).map(x=>`<figure><img src="${x.src}"><figcaption>${esc(x.note)}<br>${new Date(x.date).toLocaleDateString()}</figcaption></figure>`).join('')}</div></article><article class="card wide"><h2>Clickable history timeline</h2>${ls.map(l=>`<details class="log"><summary><b>${new Date(l.date).toLocaleString()} • ${esc((allWorkouts().find(w=>w.id===l.planId)||{}).title||'Workout')}</b></summary><p>Duration ${l.duration} min • reps ${l.reps||0} • steps ${l.steps||0} • miles ${((l.distanceKm||0)*.621371).toFixed(2)} • HR ${l.avgHr||'n/a'} • calories ${l.calories||calories(p(),l)}</p><p>Before: ${JSON.stringify(l.before||{})}</p><p>After: ${JSON.stringify(l.after||{})}</p><p>Improvements: ${(l.events||[]).map(e=>e.message).join('; ')||'No corrections logged.'}</p></details>`).join('')||'<p>No workout history yet.</p>'}</article></section>`;$('#savePhoto').onclick=savePhoto;}
function savePhoto(){let file=$('#photo').files[0];if(!file)return;let r=new FileReader();r.onload=()=>{state.photos.unshift({id:crypto.randomUUID(),profileId:p().id,date:new Date().toISOString(),note:val('#photoNote'),src:r.result});timeline()};r.readAsDataURL(file)}
function profilePage(){let pr=p();$('#panel').innerHTML=`<section class="deck-grid"><article class="card"><h2>Required athlete info</h2>${field('name','Name',pr.name)}${field('birthday','Birthday',pr.birthday,'date')}<label>Sex<select id="sex"><option value="">select</option><option ${pr.sex==='male'?'selected':''} value="male">male</option><option ${pr.sex==='female'?'selected':''} value="female">female</option><option ${pr.sex==='other'?'selected':''} value="other">other/prefer not to say</option></select></label><div class="split"><label>Height ft<input id="heightFt" type="number" value="${pr.heightFt}"></label><label>in<input id="heightIn" type="number" value="${pr.heightIn}"></label></div>${field('weightLb','Weight lb',pr.weightLb,'number')}<label>Average weekly workout<select id="level"><option ${pr.level==='low'?'selected':''}>low</option><option ${pr.level==='medium'?'selected':''}>medium</option><option ${pr.level==='high'?'selected':''}>high</option></select></label>${field('limitations','Limitations / injuries',pr.limitations)}<button id="saveProfile">Save info</button></article><article class="card"><h2>Profile picture</h2><div class="profile-pic">${pr.pic?`<img src="${pr.pic}">`:'No picture yet'}</div><input id="pic" type="file" accept="image/*"><button id="savePic">Save picture</button><p class="muted">To use another profile, hit Log out, then log into that name with its PIN. No in-app profile switching.</p></article></section>`;$('#saveProfile').onclick=()=>{Object.assign(pr,{name:val('#name'),birthday:val('#birthday'),age:ageOf(pr),sex:val('#sex'),heightFt:+val('#heightFt'),heightIn:+val('#heightIn'),weightLb:+val('#weightLb'),level:val('#level'),limitations:val('#limitations')});render()};$('#savePic').onclick=()=>{let f=$('#pic').files[0];if(!f)return;let r=new FileReader();r.onload=()=>{pr.pic=r.result;render()};r.readAsDataURL(f)}}function field(id,label,value,type='text'){return`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`}
function saveLog(w,events,data){state.logs.unshift({id:crypto.randomUUID(),profileId:p().id,planId:w.id,date:new Date().toISOString(),duration:data.duration||w.duration,effort:data.effort||3,steps:data.steps||0,distanceKm:data.distanceKm||0,avgHr:data.avgHr,calories:data.calories,notes:data.notes||'',events,reps:data.reps,before:data.before,after:data.after});save()}
function totals(){let ls=logs();return{workouts:ls.length,minutes:ls.reduce((a,l)=>a+l.duration,0),miles:ls.reduce((a,l)=>a+(l.distanceKm||0),0)*.621371,cal:ls.reduce((a,l)=>a+(l.calories||calories(p(),l)),0)}}function calories(pr,l){return Math.round(([2.5,3.5,5,7,9][(l.effort||3)-1])*3.5*weightKg(pr)/200*l.duration)}
function series(){let arr=logs().slice().reverse().slice(-14);return[{data:arr.map(l=>l.duration)},{data:arr.map(l=>(l.distanceKm||0)*6.21*10)},{data:arr.map(l=>(l.calories||calories(p(),l))/50)}]}function drawChart(id,ser,labels){let c=document.getElementById(id),ctx=c?.getContext('2d');if(!ctx)return;let w=c.width=c.clientWidth*devicePixelRatio,h=c.height=(+c.getAttribute('height')||240)*devicePixelRatio;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,215,0,.2)';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(30,h*i/5);ctx.lineTo(w-20,h*i/5);ctx.stroke()}let max=Math.max(10,...ser.flatMap(s=>s.data));['#ffd700','#fff3a3','#c69200'].forEach((col,si)=>{let s=ser[si]||{data:[]};ctx.strokeStyle=col;ctx.lineWidth=4;ctx.beginPath();s.data.forEach((v,i)=>{let x=40+i*((w-70)/Math.max(1,s.data.length-1)),y=h-25-v/max*(h-55);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});ctx.fillStyle='#ffd700';ctx.font=`${13*devicePixelRatio}px sans-serif`;labels.forEach((l,i)=>ctx.fillText(l,35+i*130*devicePixelRatio,20*devicePixelRatio))}
render();
